spring:
  application:
    name: ledger

  datasource:
    url: jdbc:mysql://localhost:3306/ledger_db #local, github actions, ec2 전부 각 컴퓨터 자신의 MySQL을 가리키므로 환경변수 처리 제외
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 900000
