-- ============================================================
-- V1: Ledger V3.0 초기 스키마 (전체 통합)
-- 최초 배포 전 단계이므로 기존 V1~V5 개발 중 마이그레이션을
-- 하나의 초기 스키마로 통합했습니다.
-- 이 파일을 실제 환경에 최초 적용한 이후부터는, 이 파일을
-- 수정하지 않고 변경 사항을 V2, V3... 순서로 새로 추가합니다.
-- ============================================================

-- ------------------------------------------------------------
-- 1. 회원 / 인증
-- ------------------------------------------------------------

CREATE TABLE USERS (
    USER_NUM             INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID               VARCHAR(30),
    USER_PW                VARCHAR(100),
    USER_NICKNAME     VARCHAR(60)  NOT NULL,
    USER_EMAIL          VARCHAR(100) NOT NULL,
    USER_PHONE          VARCHAR(13),
    USER_BIRTH          VARCHAR(8),
    USER_STATUS         CHAR(1)      NOT NULL DEFAULT 'A',
    LOGIN_FAIL_COUNT   INT          NOT NULL DEFAULT 0,
    LOCKED_UNTIL        DATETIME,
    BOOK_OPEN_YN       CHAR(1)      NOT NULL DEFAULT 'N',
    SIGNUP_IP           VARCHAR(45),
    USER_CREATED_AT   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    USER_LAST_LOGIN_AT DATETIME,
    UNIQUE KEY UK_USER_ID (USER_ID),
    UNIQUE KEY UK_USER_EMAIL (USER_EMAIL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE REFRESH_TOKENS (
    TOKEN_NUM     INT AUTO_INCREMENT PRIMARY KEY,
    USER_NUM      INT NOT NULL,
    TOKEN_HASH    VARCHAR(255) NOT NULL,
    EXPIRES_AT    DATETIME NOT NULL,
    REVOKED_YN    CHAR(1) NOT NULL DEFAULT 'N',
    CREATED_AT    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_TOKEN_USER FOREIGN KEY (USER_NUM) REFERENCES USERS(USER_NUM),
    KEY IDX_TOKEN_USER_REVOKED (USER_NUM, REVOKED_YN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE AUTH_VERIFICATIONS (
    VERIFY_NUM    INT AUTO_INCREMENT PRIMARY KEY,
    USER_NUM      INT NOT NULL,
    VERIFY_TYPE   CHAR(1) NOT NULL,
    VERIFY_TOKEN  VARCHAR(255) NOT NULL,
    EXPIRES_AT    DATETIME NOT NULL,
    USED_YN       CHAR(1) NOT NULL DEFAULT 'N',
    CREATED_AT    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_VERIFY_USER FOREIGN KEY (USER_NUM) REFERENCES USERS(USER_NUM),
    UNIQUE KEY UK_VERIFY_TOKEN (VERIFY_TOKEN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE AI_USAGE_LOGS (
    LOG_NUM         INT AUTO_INCREMENT PRIMARY KEY,
    USER_NUM         INT NOT NULL,
    ENDPOINT_TYPE     CHAR(1) NOT NULL,
    SUCCESS_YN         CHAR(1) NOT NULL,
    CREATED_AT          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_AILOG_USER FOREIGN KEY (USER_NUM) REFERENCES USERS(USER_NUM),
    KEY IDX_AILOG_USER_CREATED (USER_NUM, CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE SOCIAL_ACCOUNTS (
    SOCIAL_NUM           INT AUTO_INCREMENT PRIMARY KEY,
    USER_NUM              INT NOT NULL,
    PROVIDER               CHAR(1) NOT NULL,
    PROVIDER_USER_ID        VARCHAR(100) NOT NULL,
    CONNECTED_AT            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_SOCIAL_USER FOREIGN KEY (USER_NUM) REFERENCES USERS(USER_NUM),
    UNIQUE KEY UK_SOCIAL_PROVIDER_PID (PROVIDER, PROVIDER_USER_ID),
    UNIQUE KEY UK_SOCIAL_USER_PROVIDER (USER_NUM, PROVIDER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ------------------------------------------------------------
-- 2. 개인 가계부
-- ------------------------------------------------------------

CREATE TABLE PERSONAL_CATEGORIES (
    CATEGORY_NUM         INT AUTO_INCREMENT PRIMARY KEY,
    USER_NUM             INT NOT NULL,
    PARENT_CATEGORY_NUM  INT,
    CATEGORY_NAME        VARCHAR(20) NOT NULL,
    CATEGORY_EMOJI       VARCHAR(10),
    CATEGORY_TYPE        CHAR(1) NOT NULL,
    IS_DEFAULT_YN         CHAR(1) NOT NULL DEFAULT 'N',
    USE_YN                CHAR(1) NOT NULL DEFAULT 'Y',
    CREATED_AT            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PCAT_USER FOREIGN KEY (USER_NUM) REFERENCES USERS(USER_NUM),
    CONSTRAINT FK_PCAT_PARENT FOREIGN KEY (PARENT_CATEGORY_NUM) REFERENCES PERSONAL_CATEGORIES(CATEGORY_NUM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE PERSONAL_TRANSACTIONS (
    TRANS_NUM         INT AUTO_INCREMENT PRIMARY KEY,
    USER_NUM          INT NOT NULL,
    CATEGORY_NUM      INT NOT NULL,
    TRANS_TYPE        CHAR(1) NOT NULL,
    TRANS_AMOUNT      BIGINT NOT NULL,
    TRANS_DATE        DATE NOT NULL,
    TRANS_MEMO        VARCHAR(100),
    PLACE_NAME        VARCHAR(100),
    LATITUDE          DECIMAL(10,7),
    LONGITUDE         DECIMAL(10,7),
    CAPTURE_IMG_URL   VARCHAR(500),
    AI_ANALYZED_YN    CHAR(1) NOT NULL DEFAULT 'N',
    VERSION           INT NOT NULL DEFAULT 0,
    USE_YN            CHAR(1) NOT NULL DEFAULT 'Y',
    CREATED_AT        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PTRANS_USER FOREIGN KEY (USER_NUM) REFERENCES USERS(USER_NUM),
    CONSTRAINT FK_PTRANS_CATEGORY FOREIGN KEY (CATEGORY_NUM) REFERENCES PERSONAL_CATEGORIES(CATEGORY_NUM),
    CONSTRAINT CHK_PTRANS_AMOUNT CHECK (TRANS_AMOUNT > 0),
    KEY IDX_PTRANS_USER_DATE (USER_NUM, TRANS_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ------------------------------------------------------------
-- 3. 공동 가계부
-- ------------------------------------------------------------

CREATE TABLE `GROUPS` (
    GROUP_NUM          INT AUTO_INCREMENT PRIMARY KEY,
    GROUP_NAME          VARCHAR(20) NOT NULL,
    GROUP_DESC          VARCHAR(300),
    GROUP_TYPE          CHAR(1) NOT NULL,
    GROUP_OWNER_NUM     INT NOT NULL,
    GROUP_OPEN_YN       CHAR(1) NOT NULL DEFAULT 'N',
    SETTLE_USE_YN       CHAR(1) NOT NULL DEFAULT 'Y',
    USE_YN               CHAR(1) NOT NULL DEFAULT 'Y',
    CREATED_AT           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_GROUP_OWNER FOREIGN KEY (GROUP_OWNER_NUM) REFERENCES USERS(USER_NUM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE GROUP_MEMBERS (
    MEMBER_NUM      INT AUTO_INCREMENT PRIMARY KEY,
    GROUP_NUM        INT NOT NULL,
    USER_NUM         INT NOT NULL,
    JOIN_DATE        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MEMBER_STATUS    CHAR(1) NOT NULL DEFAULT 'A',
    CONSTRAINT FK_GMEMBER_GROUP FOREIGN KEY (GROUP_NUM) REFERENCES `GROUPS`(GROUP_NUM),
    CONSTRAINT FK_GMEMBER_USER FOREIGN KEY (USER_NUM) REFERENCES USERS(USER_NUM),
    KEY IDX_GMEMBER_USER_STATUS (USER_NUM, MEMBER_STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE GROUP_CATEGORIES (
    GCATEGORY_NUM        INT AUTO_INCREMENT PRIMARY KEY,
    GROUP_NUM             INT NOT NULL,
    PARENT_CATEGORY_NUM   INT,
    CATEGORY_NAME         VARCHAR(20) NOT NULL,
    CATEGORY_EMOJI        VARCHAR(10),
    IS_DEFAULT_YN          CHAR(1) NOT NULL DEFAULT 'N',
    USE_YN                 CHAR(1) NOT NULL DEFAULT 'Y',
    CREATED_AT             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_GCAT_GROUP FOREIGN KEY (GROUP_NUM) REFERENCES `GROUPS`(GROUP_NUM),
    CONSTRAINT FK_GCAT_PARENT FOREIGN KEY (PARENT_CATEGORY_NUM) REFERENCES GROUP_CATEGORIES(GCATEGORY_NUM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE GROUP_MERCHANT_PROFILES (
    PROFILE_NUM         INT AUTO_INCREMENT PRIMARY KEY,
    GROUP_NUM            INT NOT NULL,
    MERCHANT_NAME         VARCHAR(200) NOT NULL,
    EMBEDDING_VECTOR       JSON NOT NULL,
    LAST_GCATEGORY_NUM     INT NOT NULL,
    LAST_MEMO              VARCHAR(100),
    USAGE_COUNT            INT NOT NULL DEFAULT 1,
    UPDATED_AT             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREATED_AT             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_GMERCHANT_GROUP FOREIGN KEY (GROUP_NUM) REFERENCES `GROUPS`(GROUP_NUM),
    CONSTRAINT FK_GMERCHANT_CATEGORY FOREIGN KEY (LAST_GCATEGORY_NUM) REFERENCES GROUP_CATEGORIES(GCATEGORY_NUM),
    KEY IDX_GMERCHANT_GROUP_NAME (GROUP_NUM, MERCHANT_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE LEDGER_PERIODS (
    PERIOD_NUM         INT AUTO_INCREMENT PRIMARY KEY,
    GROUP_NUM           INT NOT NULL,
    PERIOD_SEQ           INT NOT NULL,
    PERIOD_START_DATE     DATETIME NOT NULL,
    PERIOD_END_DATE       DATETIME,
    PERIOD_STATUS         CHAR(1) NOT NULL DEFAULT 'O',
    CREATED_AT             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PERIOD_GROUP FOREIGN KEY (GROUP_NUM) REFERENCES `GROUPS`(GROUP_NUM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE GROUP_TRANSACTIONS (
    GTRANS_NUM        INT AUTO_INCREMENT PRIMARY KEY,
    GROUP_NUM          INT NOT NULL,
    PERIOD_NUM         INT NOT NULL,
    GCATEGORY_NUM      INT NOT NULL,
    USER_NUM           INT NOT NULL,
    TRANS_AMOUNT       BIGINT NOT NULL,
    TRANS_DATE         DATE NOT NULL,
    TRANS_MEMO         VARCHAR(100),
    PLACE_NAME         VARCHAR(100),
    LATITUDE           DECIMAL(10,7),
    LONGITUDE          DECIMAL(10,7),
    CAPTURE_IMG_URL    VARCHAR(500),
    VERSION            INT NOT NULL DEFAULT 0,
    USE_YN             CHAR(1) NOT NULL DEFAULT 'Y',
    CREATED_AT          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_GTRANS_GROUP FOREIGN KEY (GROUP_NUM) REFERENCES `GROUPS`(GROUP_NUM),
    CONSTRAINT FK_GTRANS_PERIOD FOREIGN KEY (PERIOD_NUM) REFERENCES LEDGER_PERIODS(PERIOD_NUM),
    CONSTRAINT FK_GTRANS_CATEGORY FOREIGN KEY (GCATEGORY_NUM) REFERENCES GROUP_CATEGORIES(GCATEGORY_NUM),
    CONSTRAINT FK_GTRANS_USER FOREIGN KEY (USER_NUM) REFERENCES USERS(USER_NUM),
    CONSTRAINT CHK_GTRANS_AMOUNT CHECK (TRANS_AMOUNT > 0),
    KEY IDX_GTRANS_GROUP_DATE (GROUP_NUM, TRANS_DATE),
    KEY IDX_GTRANS_PERIOD (PERIOD_NUM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE SETTLEMENT_SNAPSHOTS (
    SETTLE_NUM          INT AUTO_INCREMENT PRIMARY KEY,
    PERIOD_NUM           INT NOT NULL,
    PAYER_USER_NUM        INT NOT NULL,
    RECEIVER_USER_NUM     INT NOT NULL,
    SETTLE_AMOUNT         BIGINT NOT NULL,
    MATCH_SEQ             INT NOT NULL,
    CREATED_AT             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_SETTLE_PERIOD FOREIGN KEY (PERIOD_NUM) REFERENCES LEDGER_PERIODS(PERIOD_NUM),
    CONSTRAINT FK_SETTLE_PAYER FOREIGN KEY (PAYER_USER_NUM) REFERENCES USERS(USER_NUM),
    CONSTRAINT FK_SETTLE_RECEIVER FOREIGN KEY (RECEIVER_USER_NUM) REFERENCES USERS(USER_NUM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE EXPENSE_LOGS (
    LOG_NUM             INT AUTO_INCREMENT PRIMARY KEY,
    GTRANS_NUM           INT NOT NULL,
    ACTION_USER_NUM       INT NOT NULL,
    ACTION_TYPE           CHAR(1) NOT NULL,
    BEFORE_AMOUNT          BIGINT NOT NULL,
    AFTER_AMOUNT           BIGINT,
    BEFORE_CATEGORY        VARCHAR(20) NOT NULL,
    AFTER_CATEGORY         VARCHAR(20),
    BEFORE_MEMO            VARCHAR(100),
    AFTER_MEMO              VARCHAR(100),
    BEFORE_DATE             DATE,
    AFTER_DATE               DATE,
    CREATED_AT               DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_LOG_GTRANS FOREIGN KEY (GTRANS_NUM) REFERENCES GROUP_TRANSACTIONS(GTRANS_NUM),
    CONSTRAINT FK_LOG_USER FOREIGN KEY (ACTION_USER_NUM) REFERENCES USERS(USER_NUM),
    KEY IDX_LOG_GTRANS_CREATED (GTRANS_NUM, CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE INVITATIONS (
    INVITE_NUM       INT AUTO_INCREMENT PRIMARY KEY,
    GROUP_NUM         INT NOT NULL,
    INVITER_NUM        INT NOT NULL,
    INVITEE_NUM        INT NOT NULL,
    INVITE_STATUS      CHAR(1) NOT NULL DEFAULT 'W',
    CREATED_AT          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_INVITE_GROUP FOREIGN KEY (GROUP_NUM) REFERENCES `GROUPS`(GROUP_NUM),
    CONSTRAINT FK_INVITE_INVITER FOREIGN KEY (INVITER_NUM) REFERENCES USERS(USER_NUM),
    CONSTRAINT FK_INVITE_INVITEE FOREIGN KEY (INVITEE_NUM) REFERENCES USERS(USER_NUM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ------------------------------------------------------------
-- 4. AI 파싱 파이프라인 (개인·공동 공용)
-- ------------------------------------------------------------

CREATE TABLE RECEIPT_ANALYSIS (
    ANALYSIS_NUM         INT AUTO_INCREMENT PRIMARY KEY,
    USER_NUM             INT NOT NULL,
    TARGET_TYPE           CHAR(1) NOT NULL DEFAULT 'P',
    GROUP_NUM             INT,
    IMG_URL               VARCHAR(500) NOT NULL,
    OCR_RAW_TEXT          TEXT,
    PARSE_METHOD          CHAR(1),
    SUGGESTED_AMOUNT       BIGINT,
    SUGGESTED_DATE          DATE,
    SUGGESTED_MERCHANT     VARCHAR(200),
    SUGGESTED_CATEGORY     VARCHAR(20),
    CATEGORY_SOURCE        CHAR(1),
    ANALYSIS_STATUS        CHAR(1) NOT NULL DEFAULT 'P',
    CONFIRMED_PTRANS_NUM   INT,
    CONFIRMED_GTRANS_NUM   INT,
    CREATED_AT              DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ANALYSIS_USER FOREIGN KEY (USER_NUM) REFERENCES USERS(USER_NUM),
    CONSTRAINT FK_ANALYSIS_GROUP FOREIGN KEY (GROUP_NUM) REFERENCES `GROUPS`(GROUP_NUM),
    CONSTRAINT FK_ANALYSIS_PTRANS FOREIGN KEY (CONFIRMED_PTRANS_NUM) REFERENCES PERSONAL_TRANSACTIONS(TRANS_NUM),
    CONSTRAINT FK_ANALYSIS_GTRANS FOREIGN KEY (CONFIRMED_GTRANS_NUM) REFERENCES GROUP_TRANSACTIONS(GTRANS_NUM),
    KEY IDX_ANALYSIS_STATUS_CREATED (ANALYSIS_STATUS, CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE MERCHANT_PROFILES (
    PROFILE_NUM         INT AUTO_INCREMENT PRIMARY KEY,
    USER_NUM            INT NOT NULL,
    MERCHANT_NAME        VARCHAR(200) NOT NULL,
    EMBEDDING_VECTOR      JSON NOT NULL,
    LAST_CATEGORY_NUM     INT NOT NULL,
    LAST_MEMO             VARCHAR(100),
    USAGE_COUNT           INT NOT NULL DEFAULT 1,
    UPDATED_AT            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREATED_AT            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_MERCHANT_USER FOREIGN KEY (USER_NUM) REFERENCES USERS(USER_NUM),
    CONSTRAINT FK_MERCHANT_CATEGORY FOREIGN KEY (LAST_CATEGORY_NUM) REFERENCES PERSONAL_CATEGORIES(CATEGORY_NUM),
    KEY IDX_MERCHANT_USER_NAME (USER_NUM, MERCHANT_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

